// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package maintenancemode.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the MaintenanceMode module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Disable_MaintenanceModeBuilder(
		maintenancemode.proxies.MaintenanceMode _maintenance
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MaintenanceMode.ACT_Disable_MaintenanceMode");
		builder = builder.withParam("Maintenance", _maintenance);
		return builder;
	}

	public static void aCT_Disable_MaintenanceMode(
		IContext context,
		maintenancemode.proxies.MaintenanceMode _maintenance
	)
	{
		aCT_Disable_MaintenanceModeBuilder(
				_maintenance
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Enable_MaintenanceModeBuilder(
		maintenancemode.proxies.MaintenanceMode _maintenance
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MaintenanceMode.ACT_Enable_MaintenanceMode");
		builder = builder.withParam("Maintenance", _maintenance);
		return builder;
	}

	public static void aCT_Enable_MaintenanceMode(
		IContext context,
		maintenancemode.proxies.MaintenanceMode _maintenance
	)
	{
		aCT_Enable_MaintenanceModeBuilder(
				_maintenance
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_OpenMaintenancePage_If_MaintenanceModeEnabledBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MaintenanceMode.ACT_OpenMaintenancePage_If_MaintenanceModeEnabled");
		return builder;
	}

	public static boolean aCT_OpenMaintenancePage_If_MaintenanceModeEnabled(IContext context)
	{
		Object result = aCT_OpenMaintenancePage_If_MaintenanceModeEnabledBuilder().execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_GetOrCreate_MaintenanceModeBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MaintenanceMode.DS_GetOrCreate_MaintenanceMode");
		return builder;
	}

	public static maintenancemode.proxies.MaintenanceMode dS_GetOrCreate_MaintenanceMode(IContext context)
	{
		Object result = dS_GetOrCreate_MaintenanceModeBuilder().execute(context);
		return result == null ? null : maintenancemode.proxies.MaintenanceMode.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_GetOrCreate_UserRoleSettingsBuilder(
		system.proxies.UserRole _userRole
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MaintenanceMode.DS_GetOrCreate_UserRoleSettings");
		builder = builder.withParam("UserRole", _userRole);
		return builder;
	}

	public static maintenancemode.proxies.UserRoleSettings dS_GetOrCreate_UserRoleSettings(
		IContext context,
		system.proxies.UserRole _userRole
	)
	{
		Object result = dS_GetOrCreate_UserRoleSettingsBuilder(
				_userRole
			)
			.execute(context);
		return result == null ? null : maintenancemode.proxies.UserRoleSettings.initialize(context, (IMendixObject) result);
	}
}
